---

- hosts: otus-vm
  become: yes
  gather_facts: no
  tasks:
  - name: Wait 600 seconds for target connection to become reachable/usable
    ansible.builtin.wait_for_connection:
  - name: Install nginx
    apt:
      name: nginx
      state: present
      update_cache: yes
  - name: Enable and start nginx
    service:
      name: nginx
      enabled: yes
      state: started
      
